services:
  - type: web
    name: mikelogic
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn mikelogic.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: mikelogic.settings
