# Generated by Django 5.2.4 on 2025-07-04 22:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vlog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vlogpost",
            name="audio_note",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="audio"
            ),
        ),
        migrations.AlterField(
            model_name="vlogpost",
            name="video_file",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="video"
            ),
        ),
    ]
